/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.algod.client.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AssetFreezeTransactionType contains the additional fields for an asset freeze transaction
 */
@ApiModel(description = "AssetFreezeTransactionType contains the additional fields for an asset freeze transaction")

public class AssetFreezeTransactionType {
  @SerializedName("acct")
  private String acct = null;

  @SerializedName("freeze")
  private Boolean freeze = null;

  @SerializedName("id")
  private java.math.BigInteger id = null;

  public AssetFreezeTransactionType acct(String acct) {
    this.acct = acct;
    return this;
  }

   /**
   * Account specifies the account where the asset is being frozen or thawed.
   * @return acct
  **/
  @ApiModelProperty(required = true, value = "Account specifies the account where the asset is being frozen or thawed.")
  public String getAcct() {
    return acct;
  }

  public void setAcct(String acct) {
    this.acct = acct;
  }

  public AssetFreezeTransactionType freeze(Boolean freeze) {
    this.freeze = freeze;
    return this;
  }

   /**
   * NewFreezeStatus specifies the new freeze status.
   * @return freeze
  **/
  @ApiModelProperty(required = true, value = "NewFreezeStatus specifies the new freeze status.")
  public Boolean isFreeze() {
    return freeze;
  }

  public void setFreeze(Boolean freeze) {
    this.freeze = freeze;
  }

  public AssetFreezeTransactionType id(java.math.BigInteger id) {
    this.id = id;
    return this;
  }

   /**
   * AssetID is the asset being configured (or empty if creating)
   * @return id
  **/
  @ApiModelProperty(required = true, value = "AssetID is the asset being configured (or empty if creating)")
  public java.math.BigInteger getId() {
    return id;
  }

  public void setId(java.math.BigInteger id) {
    this.id = id;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    AssetFreezeTransactionType assetFreezeTransactionType = (AssetFreezeTransactionType) o;
    return ObjectUtils.equals(this.acct, assetFreezeTransactionType.acct) &&
    ObjectUtils.equals(this.freeze, assetFreezeTransactionType.freeze) &&
    ObjectUtils.equals(this.id, assetFreezeTransactionType.id);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(acct, freeze, id);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetFreezeTransactionType {\n");
    
    sb.append("    acct: ").append(toIndentedString(acct)).append("\n");
    sb.append("    freeze: ").append(toIndentedString(freeze)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

