/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.algod.client.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * KeyregTransactionType contains the additional fields for a keyreg Transaction
 */
@ApiModel(description = "KeyregTransactionType contains the additional fields for a keyreg Transaction")

public class KeyregTransactionType {
  @SerializedName("selkey")
  private byte[] selkey = null;

  @SerializedName("votefst")
  private java.math.BigInteger votefst = null;

  @SerializedName("votekd")
  private java.math.BigInteger votekd = null;

  @SerializedName("votekey")
  private byte[] votekey = null;

  @SerializedName("votelst")
  private java.math.BigInteger votelst = null;

  public KeyregTransactionType selkey(byte[] selkey) {
    this.selkey = selkey;
    return this;
  }

   /**
   * SelectionPK is the VRF public key used in key registration transactions
   * @return selkey
  **/
  @ApiModelProperty(value = "SelectionPK is the VRF public key used in key registration transactions")
  public byte[] getSelkey() {
    return selkey;
  }

  public void setSelkey(byte[] selkey) {
    this.selkey = selkey;
  }

  public KeyregTransactionType votefst(java.math.BigInteger votefst) {
    this.votefst = votefst;
    return this;
  }

   /**
   * VoteFirst is the first round this participation key is valid
   * @return votefst
  **/
  @ApiModelProperty(value = "VoteFirst is the first round this participation key is valid")
  public java.math.BigInteger getVotefst() {
    return votefst;
  }

  public void setVotefst(java.math.BigInteger votefst) {
    this.votefst = votefst;
  }

  public KeyregTransactionType votekd(java.math.BigInteger votekd) {
    this.votekd = votekd;
    return this;
  }

   /**
   * VoteKeyDilution is the dilution for the 2-level participation key
   * @return votekd
  **/
  @ApiModelProperty(value = "VoteKeyDilution is the dilution for the 2-level participation key")
  public java.math.BigInteger getVotekd() {
    return votekd;
  }

  public void setVotekd(java.math.BigInteger votekd) {
    this.votekd = votekd;
  }

  public KeyregTransactionType votekey(byte[] votekey) {
    this.votekey = votekey;
    return this;
  }

   /**
   * VotePK is the participation public key used in key registration transactions
   * @return votekey
  **/
  @ApiModelProperty(value = "VotePK is the participation public key used in key registration transactions")
  public byte[] getVotekey() {
    return votekey;
  }

  public void setVotekey(byte[] votekey) {
    this.votekey = votekey;
  }

  public KeyregTransactionType votelst(java.math.BigInteger votelst) {
    this.votelst = votelst;
    return this;
  }

   /**
   * VoteLast is the last round this participation key is valid
   * @return votelst
  **/
  @ApiModelProperty(value = "VoteLast is the last round this participation key is valid")
  public java.math.BigInteger getVotelst() {
    return votelst;
  }

  public void setVotelst(java.math.BigInteger votelst) {
    this.votelst = votelst;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    KeyregTransactionType keyregTransactionType = (KeyregTransactionType) o;
    return ObjectUtils.equals(this.selkey, keyregTransactionType.selkey) &&
    ObjectUtils.equals(this.votefst, keyregTransactionType.votefst) &&
    ObjectUtils.equals(this.votekd, keyregTransactionType.votekd) &&
    ObjectUtils.equals(this.votekey, keyregTransactionType.votekey) &&
    ObjectUtils.equals(this.votelst, keyregTransactionType.votelst);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(selkey, votefst, votekd, votekey, votelst);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class KeyregTransactionType {\n");
    
    sb.append("    selkey: ").append(toIndentedString(selkey)).append("\n");
    sb.append("    votefst: ").append(toIndentedString(votefst)).append("\n");
    sb.append("    votekd: ").append(toIndentedString(votekd)).append("\n");
    sb.append("    votekey: ").append(toIndentedString(votekey)).append("\n");
    sb.append("    votelst: ").append(toIndentedString(votelst)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

