/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.algod.client.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * TransactionResults contains information about the side effects of a transaction
 */
@ApiModel(description = "TransactionResults contains information about the side effects of a transaction")
@Deprecated
public class TransactionResults {
  @SerializedName("createdasset")
  private java.math.BigInteger createdasset = null;

  public TransactionResults createdasset(java.math.BigInteger createdasset) {
    this.createdasset = createdasset;
    return this;
  }

   /**
   * CreatedAssetIndex indicates the asset index of an asset created by this txn
   * @return createdasset
  **/
  @ApiModelProperty(value = "CreatedAssetIndex indicates the asset index of an asset created by this txn")
  public java.math.BigInteger getCreatedasset() {
    return createdasset;
  }

  public void setCreatedasset(java.math.BigInteger createdasset) {
    this.createdasset = createdasset;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    TransactionResults transactionResults = (TransactionResults) o;
    return ObjectUtils.equals(this.createdasset, transactionResults.createdasset);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(createdasset);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionResults {\n");
    
    sb.append("    createdasset: ").append(toIndentedString(createdasset)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

