/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * APIV1Wallet is the API&#39;s representation of a wallet
 */
@ApiModel(description = "APIV1Wallet is the API's representation of a wallet")

public class APIV1Wallet {
  @SerializedName("DriverName")
  private String driverName = null;

  @SerializedName("DriverVersion")
  private Integer driverVersion = null;

  @SerializedName("ID")
  private String ID = null;

  @SerializedName("Name")
  private String name = null;

  @SerializedName("SupportedTransactions")
  private List<String> supportedTransactions = null;

  @SerializedName("SupportsMnemonicUX")
  private Boolean supportsMnemonicUX = null;

  public APIV1Wallet driverName(String driverName) {
    this.driverName = driverName;
    return this;
  }

   /**
   * Get driverName
   * @return driverName
  **/
  @ApiModelProperty(value = "")
  public String getDriverName() {
    return driverName;
  }

  public void setDriverName(String driverName) {
    this.driverName = driverName;
  }

  public APIV1Wallet driverVersion(Integer driverVersion) {
    this.driverVersion = driverVersion;
    return this;
  }

   /**
   * Get driverVersion
   * @return driverVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getDriverVersion() {
    return driverVersion;
  }

  public void setDriverVersion(Integer driverVersion) {
    this.driverVersion = driverVersion;
  }

  public APIV1Wallet ID(String ID) {
    this.ID = ID;
    return this;
  }

   /**
   * Get ID
   * @return ID
  **/
  @ApiModelProperty(value = "")
  public String getID() {
    return ID;
  }

  public void setID(String ID) {
    this.ID = ID;
  }

  public APIV1Wallet name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(value = "")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public APIV1Wallet supportedTransactions(List<String> supportedTransactions) {
    this.supportedTransactions = supportedTransactions;
    return this;
  }

  public APIV1Wallet addSupportedTransactionsItem(String supportedTransactionsItem) {
    if (this.supportedTransactions == null) {
      this.supportedTransactions = new ArrayList<String>();
    }
    this.supportedTransactions.add(supportedTransactionsItem);
    return this;
  }

   /**
   * Get supportedTransactions
   * @return supportedTransactions
  **/
  @ApiModelProperty(value = "")
  public List<String> getSupportedTransactions() {
    return supportedTransactions;
  }

  public void setSupportedTransactions(List<String> supportedTransactions) {
    this.supportedTransactions = supportedTransactions;
  }

  public APIV1Wallet supportsMnemonicUX(Boolean supportsMnemonicUX) {
    this.supportsMnemonicUX = supportsMnemonicUX;
    return this;
  }

   /**
   * Get supportsMnemonicUX
   * @return supportsMnemonicUX
  **/
  @ApiModelProperty(value = "")
  public Boolean isSupportsMnemonicUX() {
    return supportsMnemonicUX;
  }

  public void setSupportsMnemonicUX(Boolean supportsMnemonicUX) {
    this.supportsMnemonicUX = supportsMnemonicUX;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1Wallet apIV1Wallet = (APIV1Wallet) o;
    return ObjectUtils.equals(this.driverName, apIV1Wallet.driverName) &&
    ObjectUtils.equals(this.driverVersion, apIV1Wallet.driverVersion) &&
    ObjectUtils.equals(this.ID, apIV1Wallet.ID) &&
    ObjectUtils.equals(this.name, apIV1Wallet.name) &&
    ObjectUtils.equals(this.supportedTransactions, apIV1Wallet.supportedTransactions) &&
    ObjectUtils.equals(this.supportsMnemonicUX, apIV1Wallet.supportsMnemonicUX);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(driverName, driverVersion, ID, name, supportedTransactions, supportsMnemonicUX);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1Wallet {\n");
    
    sb.append("    driverName: ").append(toIndentedString(driverName)).append("\n");
    sb.append("    driverVersion: ").append(toIndentedString(driverVersion)).append("\n");
    sb.append("    ID: ").append(toIndentedString(ID)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportedTransactions: ").append(toIndentedString(supportedTransactions)).append("\n");
    sb.append("    supportsMnemonicUX: ").append(toIndentedString(supportsMnemonicUX)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

