/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * APIV1POSTWalletInitRequest is the request for &#x60;POST /v1/wallet/init&#x60;
 */
@ApiModel(description = "APIV1POSTWalletInitRequest is the request for `POST /v1/wallet/init`")

public class APIV1POSTWalletInitRequest {
  @SerializedName("WalletID")
  private String walletID = null;

  @SerializedName("WalletPassword")
  private String walletPassword = null;

  public APIV1POSTWalletInitRequest walletID(String walletID) {
    this.walletID = walletID;
    return this;
  }

   /**
   * Get walletID
   * @return walletID
  **/
  @ApiModelProperty(value = "")
  public String getWalletID() {
    return walletID;
  }

  public void setWalletID(String walletID) {
    this.walletID = walletID;
  }

  public APIV1POSTWalletInitRequest walletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
    return this;
  }

   /**
   * Get walletPassword
   * @return walletPassword
  **/
  @ApiModelProperty(value = "")
  public String getWalletPassword() {
    return walletPassword;
  }

  public void setWalletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1POSTWalletInitRequest apIV1POSTWalletInitRequest = (APIV1POSTWalletInitRequest) o;
    return ObjectUtils.equals(this.walletID, apIV1POSTWalletInitRequest.walletID) &&
    ObjectUtils.equals(this.walletPassword, apIV1POSTWalletInitRequest.walletPassword);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(walletID, walletPassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1POSTWalletInitRequest {\n");
    
    sb.append("    walletID: ").append(toIndentedString(walletID)).append("\n");
    sb.append("    walletPassword: ").append(toIndentedString(walletPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

