/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * APIV1POSTKeyExportRequest is the request for &#x60;POST /v1/key/export&#x60;
 */
@ApiModel(description = "APIV1POSTKeyExportRequest is the request for `POST /v1/key/export`")

public class APIV1POSTKeyExportRequest {
  @SerializedName("PublicKey")
  private PublicKey publicKey = null;

  @SerializedName("WalletHandleToken")
  private String walletHandleToken = null;

  @SerializedName("WalletPassword")
  private String walletPassword = null;

  public APIV1POSTKeyExportRequest publicKey(PublicKey publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  @ApiModelProperty(value = "")
  public PublicKey getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(PublicKey publicKey) {
    this.publicKey = publicKey;
  }

  public APIV1POSTKeyExportRequest walletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
    return this;
  }

   /**
   * Get walletHandleToken
   * @return walletHandleToken
  **/
  @ApiModelProperty(value = "")
  public String getWalletHandleToken() {
    return walletHandleToken;
  }

  public void setWalletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
  }

  public APIV1POSTKeyExportRequest walletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
    return this;
  }

   /**
   * Get walletPassword
   * @return walletPassword
  **/
  @ApiModelProperty(value = "")
  public String getWalletPassword() {
    return walletPassword;
  }

  public void setWalletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1POSTKeyExportRequest apIV1POSTKeyExportRequest = (APIV1POSTKeyExportRequest) o;
    return ObjectUtils.equals(this.publicKey, apIV1POSTKeyExportRequest.publicKey) &&
    ObjectUtils.equals(this.walletHandleToken, apIV1POSTKeyExportRequest.walletHandleToken) &&
    ObjectUtils.equals(this.walletPassword, apIV1POSTKeyExportRequest.walletPassword);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(publicKey, walletHandleToken, walletPassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1POSTKeyExportRequest {\n");
    
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    walletHandleToken: ").append(toIndentedString(walletHandleToken)).append("\n");
    sb.append("    walletPassword: ").append(toIndentedString(walletPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

