/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * APIV1WalletHandle includes the wallet the handle corresponds to and the number of number of seconds to expiration
 */
@ApiModel(description = "APIV1WalletHandle includes the wallet the handle corresponds to and the number of number of seconds to expiration")

public class APIV1WalletHandle {
  @SerializedName("expires_seconds")
  private Long expiresSeconds = null;

  @SerializedName("wallet")
  private APIV1Wallet wallet = null;

  public APIV1WalletHandle expiresSeconds(Long expiresSeconds) {
    this.expiresSeconds = expiresSeconds;
    return this;
  }

   /**
   * Get expiresSeconds
   * @return expiresSeconds
  **/
  @ApiModelProperty(value = "")
  public Long getExpiresSeconds() {
    return expiresSeconds;
  }

  public void setExpiresSeconds(Long expiresSeconds) {
    this.expiresSeconds = expiresSeconds;
  }

  public APIV1WalletHandle wallet(APIV1Wallet wallet) {
    this.wallet = wallet;
    return this;
  }

   /**
   * Get wallet
   * @return wallet
  **/
  @ApiModelProperty(value = "")
  public APIV1Wallet getWallet() {
    return wallet;
  }

  public void setWallet(APIV1Wallet wallet) {
    this.wallet = wallet;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1WalletHandle apIV1WalletHandle = (APIV1WalletHandle) o;
    return ObjectUtils.equals(this.expiresSeconds, apIV1WalletHandle.expiresSeconds) &&
    ObjectUtils.equals(this.wallet, apIV1WalletHandle.wallet);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(expiresSeconds, wallet);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1WalletHandle {\n");
    
    sb.append("    expiresSeconds: ").append(toIndentedString(expiresSeconds)).append("\n");
    sb.append("    wallet: ").append(toIndentedString(wallet)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

