/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * APIV1POSTMultisigExportResponse is the response to &#x60;POST /v1/multisig/export&#x60; friendly:ExportMultisigResponse
 */
@ApiModel(description = "APIV1POSTMultisigExportResponse is the response to `POST /v1/multisig/export` friendly:ExportMultisigResponse")

public class APIV1POSTMultisigExportResponse {
  @SerializedName("error")
  private Boolean error = null;

  @SerializedName("message")
  private String message = null;

  @SerializedName("multisig_version")
  private Integer multisigVersion = null;

  @SerializedName("pks")
  private List<PublicKey> pks = null;

  @SerializedName("threshold")
  private Integer threshold = null;

  public APIV1POSTMultisigExportResponse error(Boolean error) {
    this.error = error;
    return this;
  }

   /**
   * Get error
   * @return error
  **/
  @ApiModelProperty(value = "")
  public Boolean isError() {
    return error;
  }

  public void setError(Boolean error) {
    this.error = error;
  }

  public APIV1POSTMultisigExportResponse message(String message) {
    this.message = message;
    return this;
  }

   /**
   * Get message
   * @return message
  **/
  @ApiModelProperty(value = "")
  public String getMessage() {
    return message;
  }

  public void setMessage(String message) {
    this.message = message;
  }

  public APIV1POSTMultisigExportResponse multisigVersion(Integer multisigVersion) {
    this.multisigVersion = multisigVersion;
    return this;
  }

   /**
   * Get multisigVersion
   * @return multisigVersion
  **/
  @ApiModelProperty(value = "")
  public Integer getMultisigVersion() {
    return multisigVersion;
  }

  public void setMultisigVersion(Integer multisigVersion) {
    this.multisigVersion = multisigVersion;
  }

  public APIV1POSTMultisigExportResponse pks(List<PublicKey> pks) {
    this.pks = pks;
    return this;
  }

  public APIV1POSTMultisigExportResponse addPksItem(PublicKey pksItem) {
    if (this.pks == null) {
      this.pks = new ArrayList<PublicKey>();
    }
    this.pks.add(pksItem);
    return this;
  }

   /**
   * Get pks
   * @return pks
  **/
  @ApiModelProperty(value = "")
  public List<PublicKey> getPks() {
    return pks;
  }

  public void setPks(List<PublicKey> pks) {
    this.pks = pks;
  }

  public APIV1POSTMultisigExportResponse threshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @ApiModelProperty(value = "")
  public Integer getThreshold() {
    return threshold;
  }

  public void setThreshold(Integer threshold) {
    this.threshold = threshold;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1POSTMultisigExportResponse apIV1POSTMultisigExportResponse = (APIV1POSTMultisigExportResponse) o;
    return ObjectUtils.equals(this.error, apIV1POSTMultisigExportResponse.error) &&
    ObjectUtils.equals(this.message, apIV1POSTMultisigExportResponse.message) &&
    ObjectUtils.equals(this.multisigVersion, apIV1POSTMultisigExportResponse.multisigVersion) &&
    ObjectUtils.equals(this.pks, apIV1POSTMultisigExportResponse.pks) &&
    ObjectUtils.equals(this.threshold, apIV1POSTMultisigExportResponse.threshold);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(error, message, multisigVersion, pks, threshold);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1POSTMultisigExportResponse {\n");
    
    sb.append("    error: ").append(toIndentedString(error)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    multisigVersion: ").append(toIndentedString(multisigVersion)).append("\n");
    sb.append("    pks: ").append(toIndentedString(pks)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

