/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * APIV1POSTMultisigTransactionSignRequest is the request for &#x60;POST /v1/multisig/sign&#x60;
 */
@ApiModel(description = "APIV1POSTMultisigTransactionSignRequest is the request for `POST /v1/multisig/sign`")

public class APIV1POSTMultisigTransactionSignRequest {
  @SerializedName("PartialMsig")
  private MultisigSig partialMsig = null;

  @SerializedName("PublicKey")
  private PublicKey publicKey = null;

  @SerializedName("Transaction")
  private List<Integer> transaction = null;

  @SerializedName("TransactionType")
  private String transactionType = null;

  @SerializedName("WalletHandleToken")
  private String walletHandleToken = null;

  @SerializedName("WalletPassword")
  private String walletPassword = null;

  public APIV1POSTMultisigTransactionSignRequest partialMsig(MultisigSig partialMsig) {
    this.partialMsig = partialMsig;
    return this;
  }

   /**
   * Get partialMsig
   * @return partialMsig
  **/
  @ApiModelProperty(value = "")
  public MultisigSig getPartialMsig() {
    return partialMsig;
  }

  public void setPartialMsig(MultisigSig partialMsig) {
    this.partialMsig = partialMsig;
  }

  public APIV1POSTMultisigTransactionSignRequest publicKey(PublicKey publicKey) {
    this.publicKey = publicKey;
    return this;
  }

   /**
   * Get publicKey
   * @return publicKey
  **/
  @ApiModelProperty(value = "")
  public PublicKey getPublicKey() {
    return publicKey;
  }

  public void setPublicKey(PublicKey publicKey) {
    this.publicKey = publicKey;
  }

  public APIV1POSTMultisigTransactionSignRequest transaction(List<Integer> transaction) {
    this.transaction = transaction;
    return this;
  }

  public APIV1POSTMultisigTransactionSignRequest addTransactionItem(Integer transactionItem) {
    if (this.transaction == null) {
      this.transaction = new ArrayList<Integer>();
    }
    this.transaction.add(transactionItem);
    return this;
  }

   /**
   * Get transaction
   * @return transaction
  **/
  @ApiModelProperty(value = "")
  public List<Integer> getTransaction() {
    return transaction;
  }

  public void setTransaction(List<Integer> transaction) {
    this.transaction = transaction;
  }

  public APIV1POSTMultisigTransactionSignRequest transactionType(String transactionType) {
    this.transactionType = transactionType;
    return this;
  }

   /**
   * Get transactionType
   * @return transactionType
  **/
  @ApiModelProperty(value = "")
  public String getTransactionType() {
    return transactionType;
  }

  public void setTransactionType(String transactionType) {
    this.transactionType = transactionType;
  }

  public APIV1POSTMultisigTransactionSignRequest walletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
    return this;
  }

   /**
   * Get walletHandleToken
   * @return walletHandleToken
  **/
  @ApiModelProperty(value = "")
  public String getWalletHandleToken() {
    return walletHandleToken;
  }

  public void setWalletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
  }

  public APIV1POSTMultisigTransactionSignRequest walletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
    return this;
  }

   /**
   * Get walletPassword
   * @return walletPassword
  **/
  @ApiModelProperty(value = "")
  public String getWalletPassword() {
    return walletPassword;
  }

  public void setWalletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1POSTMultisigTransactionSignRequest apIV1POSTMultisigTransactionSignRequest = (APIV1POSTMultisigTransactionSignRequest) o;
    return ObjectUtils.equals(this.partialMsig, apIV1POSTMultisigTransactionSignRequest.partialMsig) &&
    ObjectUtils.equals(this.publicKey, apIV1POSTMultisigTransactionSignRequest.publicKey) &&
    ObjectUtils.equals(this.transaction, apIV1POSTMultisigTransactionSignRequest.transaction) &&
    ObjectUtils.equals(this.transactionType, apIV1POSTMultisigTransactionSignRequest.transactionType) &&
    ObjectUtils.equals(this.walletHandleToken, apIV1POSTMultisigTransactionSignRequest.walletHandleToken) &&
    ObjectUtils.equals(this.walletPassword, apIV1POSTMultisigTransactionSignRequest.walletPassword);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(partialMsig, publicKey, transaction, transactionType, walletHandleToken, walletPassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1POSTMultisigTransactionSignRequest {\n");
    
    sb.append("    partialMsig: ").append(toIndentedString(partialMsig)).append("\n");
    sb.append("    publicKey: ").append(toIndentedString(publicKey)).append("\n");
    sb.append("    transaction: ").append(toIndentedString(transaction)).append("\n");
    sb.append("    transactionType: ").append(toIndentedString(transactionType)).append("\n");
    sb.append("    walletHandleToken: ").append(toIndentedString(walletHandleToken)).append("\n");
    sb.append("    walletPassword: ").append(toIndentedString(walletPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

