/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * APIV1POSTMultisigImportRequest is the request for &#x60;POST /v1/multisig/import&#x60;
 */
@ApiModel(description = "APIV1POSTMultisigImportRequest is the request for `POST /v1/multisig/import`")

public class APIV1POSTMultisigImportRequest {
  @SerializedName("PKs")
  private List<PublicKey> pks = null;

  @SerializedName("Threshold")
  private Integer threshold = null;

  @SerializedName("Version")
  private Integer version = null;

  @SerializedName("WalletHandleToken")
  private String walletHandleToken = null;

  public APIV1POSTMultisigImportRequest pks(List<PublicKey> pks) {
    this.pks = pks;
    return this;
  }

  public APIV1POSTMultisigImportRequest addPksItem(PublicKey pksItem) {
    if (this.pks == null) {
      this.pks = new ArrayList<PublicKey>();
    }
    this.pks.add(pksItem);
    return this;
  }

   /**
   * Get pks
   * @return pks
  **/
  @ApiModelProperty(value = "")
  public List<PublicKey> getPks() {
    return pks;
  }

  public void setPks(List<PublicKey> pks) {
    this.pks = pks;
  }

  public APIV1POSTMultisigImportRequest threshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

   /**
   * Get threshold
   * @return threshold
  **/
  @ApiModelProperty(value = "")
  public Integer getThreshold() {
    return threshold;
  }

  public void setThreshold(Integer threshold) {
    this.threshold = threshold;
  }

  public APIV1POSTMultisigImportRequest version(Integer version) {
    this.version = version;
    return this;
  }

   /**
   * Get version
   * @return version
  **/
  @ApiModelProperty(value = "")
  public Integer getVersion() {
    return version;
  }

  public void setVersion(Integer version) {
    this.version = version;
  }

  public APIV1POSTMultisigImportRequest walletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
    return this;
  }

   /**
   * Get walletHandleToken
   * @return walletHandleToken
  **/
  @ApiModelProperty(value = "")
  public String getWalletHandleToken() {
    return walletHandleToken;
  }

  public void setWalletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1POSTMultisigImportRequest apIV1POSTMultisigImportRequest = (APIV1POSTMultisigImportRequest) o;
    return ObjectUtils.equals(this.pks, apIV1POSTMultisigImportRequest.pks) &&
    ObjectUtils.equals(this.threshold, apIV1POSTMultisigImportRequest.threshold) &&
    ObjectUtils.equals(this.version, apIV1POSTMultisigImportRequest.version) &&
    ObjectUtils.equals(this.walletHandleToken, apIV1POSTMultisigImportRequest.walletHandleToken);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(pks, threshold, version, walletHandleToken);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1POSTMultisigImportRequest {\n");
    
    sb.append("    pks: ").append(toIndentedString(pks)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    walletHandleToken: ").append(toIndentedString(walletHandleToken)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

