/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import com.google.gson.annotations.SerializedName;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import org.apache.commons.lang3.ObjectUtils;

/**
 * APIV1POSTWalletRequest is the request for &#x60;POST /v1/wallet&#x60;
 */
@ApiModel(description = "APIV1POSTWalletRequest is the request for `POST /v1/wallet`")

public class CreateWalletRequest {
  @SerializedName("master_derivation_key")
  private byte[] masterDerivationKey = null;

  @SerializedName("wallet_driver_name")
  private String walletDriverName = null;

  @SerializedName("wallet_name")
  private String walletName = null;

  @SerializedName("wallet_password")
  private String walletPassword = null;

  public CreateWalletRequest masterDerivationKey(byte[] masterDerivationKey) {
    this.masterDerivationKey = masterDerivationKey;
    return this;
  }

   /**
   * Get masterDerivationKey
   * @return masterDerivationKey
  **/
  @ApiModelProperty(value = "")
  public byte[] getMasterDerivationKey() {
    return masterDerivationKey;
  }

  public void setMasterDerivationKey(byte[] masterDerivationKey) {
    this.masterDerivationKey = masterDerivationKey;
  }

  public CreateWalletRequest walletDriverName(String walletDriverName) {
    this.walletDriverName = walletDriverName;
    return this;
  }

   /**
   * Get walletDriverName
   * @return walletDriverName
  **/
  @ApiModelProperty(value = "")
  public String getWalletDriverName() {
    return walletDriverName;
  }

  public void setWalletDriverName(String walletDriverName) {
    this.walletDriverName = walletDriverName;
  }

  public CreateWalletRequest walletName(String walletName) {
    this.walletName = walletName;
    return this;
  }

   /**
   * Get walletName
   * @return walletName
  **/
  @ApiModelProperty(value = "")
  public String getWalletName() {
    return walletName;
  }

  public void setWalletName(String walletName) {
    this.walletName = walletName;
  }

  public CreateWalletRequest walletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
    return this;
  }

   /**
   * Get walletPassword
   * @return walletPassword
  **/
  @ApiModelProperty(value = "")
  public String getWalletPassword() {
    return walletPassword;
  }

  public void setWalletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
  }


  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    CreateWalletRequest createWalletRequest = (CreateWalletRequest) o;
    return ObjectUtils.equals(this.masterDerivationKey, createWalletRequest.masterDerivationKey) &&
    ObjectUtils.equals(this.walletDriverName, createWalletRequest.walletDriverName) &&
    ObjectUtils.equals(this.walletName, createWalletRequest.walletName) &&
    ObjectUtils.equals(this.walletPassword, createWalletRequest.walletPassword);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(masterDerivationKey, walletDriverName, walletName, walletPassword);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateWalletRequest {\n");
    
    sb.append("    masterDerivationKey: ").append(toIndentedString(masterDerivationKey)).append("\n");
    sb.append("    walletDriverName: ").append(toIndentedString(walletDriverName)).append("\n");
    sb.append("    walletName: ").append(toIndentedString(walletName)).append("\n");
    sb.append("    walletPassword: ").append(toIndentedString(walletPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

