/*
 * KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.algorand.algosdk.kmd.client.model;

import org.apache.commons.lang3.ObjectUtils;

/**
 * PublicKey
 */

public class PublicKey {

  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
      return o != null && getClass() == o.getClass();
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti();
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PublicKey {\n");
    
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

