/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is a touched-up version of models generated by swagger-codegen from algod's spec.
 */

package com.algorand.algosdk.algod.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.annotations.SerializedName;

/**
 * Account Description
 */
public class Account {

  @SerializedName("address")
  private String address = null;

  @SerializedName("amount")
  private Long amount = null;

  @SerializedName("earnings")
  private Long earnings = null;

  @SerializedName("status")
  private String status = null;
  public Account address(String address) {
    this.address = address;
    return this;
  }



  /**
   * Address indicates the account public key
   * @return address
   **/
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public Account amount(Long amount) {
    this.amount = amount;
    return this;
  }



  /**
   * Amount indicates the total number of Algos in the account
   * @return amount
   **/
  public Long getAmount() {
    return amount;
  }
  public void setAmount(Long amount) {
    this.amount = amount;
  }
  public Account earnings(Long earnings) {
    this.earnings = earnings;
    return this;
  }



  /**
   * Earnings indicates the total earnings of Algos the account has recieved
   * @return earnings
   **/
  public Long getEarnings() {
    return earnings;
  }
  public void setEarnings(Long earnings) {
    this.earnings = earnings;
  }
  public Account status(String status) {
    this.status = status;
    return this;
  }



  /**
   * Status indicates the delegation status of the account&#x27;s Algos Offline - indicates that the associated account is delegated. Online  - indicates that the associated account used as part of the delegation pool. NotParticipating - indicates that the associated account is neither a delegator nor a delegate.
   * @return status
   **/
  public String getStatus() {
    return status;
  }
  public void setStatus(String status) {
    this.status = status;
  }
  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Account account = (Account) o;
    return ObjectUtils.equals(this.address, account.address) &&
            ObjectUtils.equals(this.amount, account.amount) &&
            ObjectUtils.equals(this.earnings, account.earnings) &&
            ObjectUtils.equals(this.status, account.status);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(address, amount, earnings, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Account {\n");

    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    earnings: ").append(toIndentedString(earnings)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
