/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is a touched-up version of models generated by swagger-codegen from algod's spec.
 */

package com.algorand.algosdk.algod.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.annotations.SerializedName;

/**
 * Supply represents the current supply of Algos in the system
 */
public class Supply {

  @SerializedName("onlineMoney")
  private Long onlineMoney = null;

  @SerializedName("round")
  private Long round = null;

  @SerializedName("totalMoney")
  private Long totalMoney = null;
  public Supply onlineMoney(Long onlineMoney) {
    this.onlineMoney = onlineMoney;
    return this;
  }

  

  /**
  * OnlineMoney
  * @return onlineMoney
  **/
  public Long getOnlineMoney() {
    return onlineMoney;
  }
  public void setOnlineMoney(Long onlineMoney) {
    this.onlineMoney = onlineMoney;
  }
  public Supply round(Long round) {
    this.round = round;
    return this;
  }

  

  /**
  * Round
  * @return round
  **/
  public Long getRound() {
    return round;
  }
  public void setRound(Long round) {
    this.round = round;
  }
  public Supply totalMoney(Long totalMoney) {
    this.totalMoney = totalMoney;
    return this;
  }

  

  /**
  * TotalMoney
  * @return totalMoney
  **/
  public Long getTotalMoney() {
    return totalMoney;
  }
  public void setTotalMoney(Long totalMoney) {
    this.totalMoney = totalMoney;
  }
  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    Supply supply = (Supply) o;
    return ObjectUtils.equals(this.onlineMoney, supply.onlineMoney) &&
    ObjectUtils.equals(this.round, supply.round) &&
    ObjectUtils.equals(this.totalMoney, supply.totalMoney);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(onlineMoney, round, totalMoney);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Supply {\n");
    
    sb.append("    onlineMoney: ").append(toIndentedString(onlineMoney)).append("\n");
    sb.append("    round: ").append(toIndentedString(round)).append("\n");
    sb.append("    totalMoney: ").append(toIndentedString(totalMoney)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
