/*
 * Algod REST API.
 * API Endpoint for AlgoD Operations.
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is a touched-up version of models generated by swagger-codegen from algod's spec.
 */

package com.algorand.algosdk.algod.model;

import org.apache.commons.lang3.ObjectUtils;
import com.google.gson.annotations.SerializedName;

/**
 * TransactionParams contains the parameters that help a client construct a new transaction.
 */
public class TransactionParams {

  @SerializedName("consensusVersion")
  private String consensusVersion = null;

  @SerializedName("fee")
  private Long fee = null;

  @SerializedName("genesisID")
  private String genesisID = null;

  @SerializedName("lastRound")
  private Long lastRound = null;
  public TransactionParams consensusVersion(String consensusVersion) {
    this.consensusVersion = consensusVersion;
    return this;
  }

  

  /**
  * ConsensusVersion indicates the consensus protocol version as of LastRound.
  * @return consensusVersion
  **/
  public String getConsensusVersion() {
    return consensusVersion;
  }
  public void setConsensusVersion(String consensusVersion) {
    this.consensusVersion = consensusVersion;
  }
  public TransactionParams fee(Long fee) {
    this.fee = fee;
    return this;
  }

  

  /**
  * Fee is the suggested transaction fee
  * @return fee
  **/
  public Long getFee() {
    return fee;
  }
  public void setFee(Long fee) {
    this.fee = fee;
  }
  public TransactionParams genesisID(String genesisID) {
    this.genesisID = genesisID;
    return this;
  }

  

  /**
  * Genesis ID
  * @return genesisID
  **/
  public String getGenesisID() {
    return genesisID;
  }
  public void setGenesisID(String genesisID) {
    this.genesisID = genesisID;
  }
  public TransactionParams lastRound(Long lastRound) {
    this.lastRound = lastRound;
    return this;
  }

  

  /**
  * LastRound indicates the last round seen
  * @return lastRound
  **/
  public Long getLastRound() {
    return lastRound;
  }
  public void setLastRound(Long lastRound) {
    this.lastRound = lastRound;
  }
  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    TransactionParams transactionParams = (TransactionParams) o;
    return ObjectUtils.equals(this.consensusVersion, transactionParams.consensusVersion) &&
    ObjectUtils.equals(this.fee, transactionParams.fee) &&
    ObjectUtils.equals(this.genesisID, transactionParams.genesisID) &&
    ObjectUtils.equals(this.lastRound, transactionParams.lastRound);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(consensusVersion, fee, genesisID, lastRound);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class TransactionParams {\n");
    
    sb.append("    consensusVersion: ").append(toIndentedString(consensusVersion)).append("\n");
    sb.append("    fee: ").append(toIndentedString(fee)).append("\n");
    sb.append("    genesisID: ").append(toIndentedString(genesisID)).append("\n");
    sb.append("    lastRound: ").append(toIndentedString(lastRound)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
