/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.algorand.algosdk.kmd.model;

import com.google.gson.annotations.SerializedName;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * APIV1Wallet is the API&#x27;s representation of a wallet
 */
public class APIV1Wallet {

  @SerializedName("driver_name")
  private String driverName = null;

  @SerializedName("driver_version")
  private Integer driverVersion = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("mnemonic_ux")
  private Boolean mnemonicUx = null;

  @SerializedName("name")
  private String name = null;

  @SerializedName("supported_txs")
  private List<String> supportedTxs = null;
  public APIV1Wallet driverName(String driverName) {
    this.driverName = driverName;
    return this;
  }

  

  /**
  * Get driverName
  * @return driverName
  **/
  public String getDriverName() {
    return driverName;
  }
  public void setDriverName(String driverName) {
    this.driverName = driverName;
  }
  public APIV1Wallet driverVersion(Integer driverVersion) {
    this.driverVersion = driverVersion;
    return this;
  }

  

  /**
  * Get driverVersion
  * @return driverVersion
  **/
  public Integer getDriverVersion() {
    return driverVersion;
  }
  public void setDriverVersion(Integer driverVersion) {
    this.driverVersion = driverVersion;
  }
  public APIV1Wallet id(String id) {
    this.id = id;
    return this;
  }

  

  /**
  * Get id
  * @return id
  **/
  public String getId() {
    return id;
  }
  public void setId(String id) {
    this.id = id;
  }
  public APIV1Wallet mnemonicUx(Boolean mnemonicUx) {
    this.mnemonicUx = mnemonicUx;
    return this;
  }

  

  /**
  * Get mnemonicUx
  * @return mnemonicUx
  **/
  public Boolean isMnemonicUx() {
    return mnemonicUx;
  }
  public void setMnemonicUx(Boolean mnemonicUx) {
    this.mnemonicUx = mnemonicUx;
  }
  public APIV1Wallet name(String name) {
    this.name = name;
    return this;
  }

  

  /**
  * Get name
  * @return name
  **/
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }
  public APIV1Wallet supportedTxs(List<String> supportedTxs) {
    this.supportedTxs = supportedTxs;
    return this;
  }

  public APIV1Wallet addSupportedTxsItem(String supportedTxsItem) {
    if (this.supportedTxs == null) {
      this.supportedTxs = new ArrayList<String>();
    }
    this.supportedTxs.add(supportedTxsItem);
    return this;
  }

  /**
  * Get supportedTxs
  * @return supportedTxs
  **/
  public List<String> getSupportedTxs() {
    return supportedTxs;
  }
  public void setSupportedTxs(List<String> supportedTxs) {
    this.supportedTxs = supportedTxs;
  }
  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    APIV1Wallet apIV1Wallet = (APIV1Wallet) o;
    return ObjectUtils.equals(this.driverName, apIV1Wallet.driverName) &&
    ObjectUtils.equals(this.driverVersion, apIV1Wallet.driverVersion) &&
    ObjectUtils.equals(this.id, apIV1Wallet.id) &&
    ObjectUtils.equals(this.mnemonicUx, apIV1Wallet.mnemonicUx) &&
    ObjectUtils.equals(this.name, apIV1Wallet.name) &&
    ObjectUtils.equals(this.supportedTxs, apIV1Wallet.supportedTxs);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(driverName, driverVersion, id, mnemonicUx, name, supportedTxs);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class APIV1Wallet {\n");
    
    sb.append("    driverName: ").append(toIndentedString(driverName)).append("\n");
    sb.append("    driverVersion: ").append(toIndentedString(driverVersion)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    mnemonicUx: ").append(toIndentedString(mnemonicUx)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    supportedTxs: ").append(toIndentedString(supportedTxs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
