/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.algorand.algosdk.kmd.model;

import com.google.gson.annotations.SerializedName;
import org.apache.commons.lang3.ObjectUtils;

/**
 * APIV1POSTKeyExportRequest is the request for &#x60;POST /v1/key/export&#x60;
 */
public class ExportKeyRequest {

  @SerializedName("address")
  private String address = null;

  @SerializedName("wallet_handle_token")
  private String walletHandleToken = null;

  @SerializedName("wallet_password")
  private String walletPassword = null;
  public ExportKeyRequest address(String address) {
    this.address = address;
    return this;
  }

  

  /**
  * Get address
  * @return address
  **/
  public String getAddress() {
    return address;
  }
  public void setAddress(String address) {
    this.address = address;
  }
  public ExportKeyRequest walletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
    return this;
  }

  

  /**
  * Get walletHandleToken
  * @return walletHandleToken
  **/
  public String getWalletHandleToken() {
    return walletHandleToken;
  }
  public void setWalletHandleToken(String walletHandleToken) {
    this.walletHandleToken = walletHandleToken;
  }
  public ExportKeyRequest walletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
    return this;
  }

  

  /**
  * Get walletPassword
  * @return walletPassword
  **/
  public String getWalletPassword() {
    return walletPassword;
  }
  public void setWalletPassword(String walletPassword) {
    this.walletPassword = walletPassword;
  }
  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    ExportKeyRequest exportKeyRequest = (ExportKeyRequest) o;
    return ObjectUtils.equals(this.address, exportKeyRequest.address) &&
    ObjectUtils.equals(this.walletHandleToken, exportKeyRequest.walletHandleToken) &&
    ObjectUtils.equals(this.walletPassword, exportKeyRequest.walletPassword);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(address, walletHandleToken, walletPassword);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ExportKeyRequest {\n");
    
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    walletHandleToken: ").append(toIndentedString(walletHandleToken)).append("\n");
    sb.append("    walletPassword: ").append(toIndentedString(walletPassword)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
