/*
 * for KMD HTTP API
 * API for KMD (Key Management Daemon)
 *
 * OpenAPI spec version: 0.0.1
 * Contact: contact@algorand.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.algorand.algosdk.kmd.model;

import com.google.gson.annotations.SerializedName;
import org.apache.commons.lang3.ObjectUtils;

import java.util.ArrayList;
import java.util.List;

/**
 * MultisigSig is the structure that holds multiple Subsigs
 */
public class MultisigSig {

  @SerializedName("Subsigs")
  private List<MultisigSubsig> subsigs = null;

  @SerializedName("Threshold")
  private Integer threshold = null;

  @SerializedName("Version")
  private Integer version = null;
  public MultisigSig subsigs(List<MultisigSubsig> subsigs) {
    this.subsigs = subsigs;
    return this;
  }

  public MultisigSig addSubsigsItem(MultisigSubsig subsigsItem) {
    if (this.subsigs == null) {
      this.subsigs = new ArrayList<MultisigSubsig>();
    }
    this.subsigs.add(subsigsItem);
    return this;
  }

  /**
  * Get subsigs
  * @return subsigs
  **/
  public List<MultisigSubsig> getSubsigs() {
    return subsigs;
  }
  public void setSubsigs(List<MultisigSubsig> subsigs) {
    this.subsigs = subsigs;
  }
  public MultisigSig threshold(Integer threshold) {
    this.threshold = threshold;
    return this;
  }

  

  /**
  * Get threshold
  * @return threshold
  **/
  public Integer getThreshold() {
    return threshold;
  }
  public void setThreshold(Integer threshold) {
    this.threshold = threshold;
  }
  public MultisigSig version(Integer version) {
    this.version = version;
    return this;
  }

  

  /**
  * Get version
  * @return version
  **/
  public Integer getVersion() {
    return version;
  }
  public void setVersion(Integer version) {
    this.version = version;
  }
  @Override
  public boolean equals(java.lang.Object o) {
  if (this == o) {
    return true;
  }
  if (o == null || getClass() != o.getClass()) {
    return false;
  }
    MultisigSig multisigSig = (MultisigSig) o;
    return ObjectUtils.equals(this.subsigs, multisigSig.subsigs) &&
    ObjectUtils.equals(this.threshold, multisigSig.threshold) &&
    ObjectUtils.equals(this.version, multisigSig.version);
  }

  @Override
  public int hashCode() {
    return ObjectUtils.hashCodeMulti(subsigs, threshold, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MultisigSig {\n");
    
    sb.append("    subsigs: ").append(toIndentedString(subsigs)).append("\n");
    sb.append("    threshold: ").append(toIndentedString(threshold)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
